spring:
  datasource:
    url: jdbc:mysql://localhost:3306/coffee_shop?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: baristauser
    password: baristapass
# Show or not log for each sql query
  jpa:
    show-sql: true
# The SQL dialect makes Hibernate generate better SQL for the chosen database
    properties.hibernate.dialect: org.hibernate.dialect.MySQLDialect
# Luquibase changeset location
  liquibase.change-log: classpath:/db/liquibase-changelog.xml
# Application context
server.port: 8090
# Logging
logging:
  file: log/application.log
  level.by.shumilov: DEBUG